// Kurzgeschichte "Zone 7" - Kapitel 1
== Heute, ist die Zukunft von gestern
[quote, Franz Liszt]
Glücklich, wer mit den Verhältnissen zu brechen versteht, ehe sie ihn gebrochen haben!

Seit etwas mehr als 5 Jahren arbeite ich nun schon auf der Orbitalstation “Florida Arklab”. Gebaut und und Betrieben von SpaceX gehört sie inzwischen zur Serie der Vorzeigeprojekte von Elon Musk. Doch so schön die Arbeit hier auch ist, es war Zeit für eine Veränderung. Eigentlich war es viel mehr als nur der bloße Wille zur Veränderung. Es war meine innere und auch meine politische Einstellung, welche mich letztlich dazu brachten den Job aufzugeben und nach neuen Plätzen zur Entfaltung der eigenen Persönlichkeit zu suchen. Mark, mit dem ich schon auf einigen Projekten gemeinsam gearbeitet hatte, verließ die Station bereits vor 3 Jahren. Inzwischen bekleidet er eine gut angesehene Position im mittleren Dienst und verdient dabei überdurchschnittlich viel Geld. Sein Projekt nennt sich “Zone 7” und erscheint politisch neutral. Im letzten Urlaub hatte er mich soweit überzeugt, dass ich den Vertrag unterschrieb und meine Kündigung bei Musk einreichte. Mark selbst hatte mich angeheuert. Ja, er durfte sogar Mitarbeiter anwerben und einstellen. Im Prinzip schöne Aussichten für die Zukunft. Klingt alles rosig. Klar irgendwo wird der Pferdefuß schon lauern aber dann wäre da ja auch noch Mark als Freund. Mit ihm gemeinsam ließ sich bislang jedes Problem lösen, egal welcher Art. 

Zone 7 ist ein Projekt auf der Erde. Ein so genanntes Bio-Humanoides Projekt. Es geht um die Verbesserung der Menschen an sich. Hier ein Implantat, dort eine genetische Veränderung, dann noch die richtige Kur und fertig ist der humorvolle Pappi mit Ninja Verteidigungskünsten. Dieser wird dann gern durch die Frau von Welt oder eigentlich der Frau mit Geld gemietet, damit er sie und ihre Kinder auf ihren langweilig öden Shopping Touren durch alle Zonen der neuen Erde begleitet und beschützt. Fern ab von Vater und restlicher Familie versteht sich. “Entspanntes Einkaufen mit Wohlfühlfaktor” so der Slogan einiger Agenturen. Besonders gut geratene Exemplare konnten sich hin und wieder auch ein kleines Zubrot durch die Bespaßung der Mieterin verdienen. Wobei dieses Zubrot oft auch schon durch den Genuß an sich als abgegolten angesehen wurde. 

Klar, dass diese Art Mann nicht von der Natur wie am Fließband produziert wurde. Hier war schon eine gute Kombination der Gene und ein push up bestimmter Körperteile nötig um alle Anforderungen erfüllen zu können. Nichts für ungut aber ich rede hier von Muskelverstärkern, Sprunginjektoren, etc. sowie  neuen Methoden wie der aus Japan stammenden Technik des Nerven Spleißens. Heraus kommen dabei Augments, wie wir sie aus der Geschichte bereits von den Eugenischen Kriegen her kennen. Hinter all dem stand diesmal nicht Monsanto als Auftraggeber sondern eine australische Tochter des japanischen Biotechnologie Konzerns Suntory. Eben jene australische Firma welche im 20. Jahrhundert durch die genetische “Züchtung” der blauen Rosenart “Applause” bekannt geworden war und seither ihre Vormachtstellung am Markt kontinuierlich auszubauen verstanden hat. 

Natürlich gelangten die “Erbauer” der neuen Augments früher oder später zu der Erkenntnis, dass ihre Exemplare sich besonders gut entwickelten wenn das soziale Umfeld stimmte. Und dieses zu schaffen, eine Stadt, eine Infrastruktur eine Gegend in welcher sich der gezüchtete Augment wohl fühlte, gab es das Infrastruktur Management von Zone 7, welches dies als seine Aufgabe beherzigte. Doch dort würde ich nicht arbeiten. Ich werde laut Mark direkt an der Forschung und Entwicklung der Augments beteiligt sein. Ein spannender Job, keine Frage!

“Sagst Du nicht mehr Tschüß?” ruft mir Sigi zu, als ich die Rampe zur Союз (Sojus) Kapsel entlang laufe. Ja einige Dinge ändern sich wohl nie. Die billigen Союз Kapseln werden aus Kostengründen bereits seit über 2 Jahrhunderten zum Transport zwischen Erde und Orbit verwendet. Die wiederverwendbare Technik von SpaceX kommt nur auf Langstrecken- und interstellaren Flügen zum Einsatz. “Doch, später.” erwidere ich. “Ich will nur gerade meinen Proviant verstauen gehen.” Proviant trifft es eigentlich nicht, denn Essen und Trinken werden vom Transportunternehmen gestellt und befinden sich bereits in der Kapsel. Eigentlich handelt es sich um mein gesamtes Hab und Gut. All das, was die alten Seeleute in ihrem Seesack mit sich führten. “Dann schau bei mir vorbei! Ich bin heute im Frachtraum 16. Beim Entrosten.” rief Sigi zurück. Sein Arm zuckte dabei auffällig und deutete mir an, dass er etwas aufgeregt war. 
