// Kurzgeschichte "Zone 7" - Kapitel 2
[#reise]
== Der Weg ist das Ziel
[quote, Marie von Ebner-Eschenbach]
Wer ans Ziel getragen wurde; darf nicht glauben; es erreicht zu haben. 

Zone 7 war eine auf dem Reißbrett entstandene und ins Nichts gebaute Stadt. Sie lag mitten in der Wüste Gobi. Nach dem Vorbild von Las Vegas bezog auch sie ihre Wasservorräte aus meilenweit entfernten Reservoiren. Zone 7 war eine rein funktionale Stadt. Ihre einzige Aufgabe bestand darin, den Einwohnern Ruhe und Erholung zu verschaffen. Die üblichen Probleme wie Ruhestörender Lärm, Schlägereien, Gewalt und Kriminalität sollten von vornherein durch eine präventive Architektur vermieden werden. Das alles sollte funktionieren obgleich unterschiedlichste Kulturen, Jahrgänge und Menschen diverser Attitüden und Habita zusammen leben sollten. Aus den Eugenischen Kriegen war das Konfliktpotential dieser Art ausführlich bekannt, dokumentiert und nicht nur für dieses Projekt aufgearbeitet wurden. 

Meine Союз Kapsel wässerte planmäßig gegen 06:00 Uhr Ortszeit im Gelben Meer. In der Nähe parkten bereits unsere beiden autonomen Flugtaxis welche in dieser Gegend standardmäßig in der Amphibienvariante bereitgestellt werden. Als wir die Ausstiegsluke öffneten nährten sich unsere Taxis bereits. “So dann machs gut.” rief mir Holden zum Abschied zu. “War ja ein echt luxuriöser Flug. Obgleich es natürlich schade war, dass wir die Dame nicht kennen lernen durften.” In einer Союз Kapsel werden normalerweise 3 Personen transportiert. Doch die 3. Person, eine Frau, hatte ihren Flug leider kurzfristig storniert und so blieb ihr Sitz leer. Was für uns natürlich mehr Platz, mehr Luft und mehr Essen und Trinken bedeutete. Leider bedeutete es auch die übliche Trostlosigkeit, Einsilbigkeit und Ödheit wie sie in der Arbeitswelt unter Männern üblich war. Ein lustiges, aufmunterndes Gespräch entfiel damit leider. “Ja, machs besser Jim!” rief ich ihm zurück. “Vielleicht sieht man sich mal in einer Zwischenzone.” “Wenn überhaupt, dann Hongkong. In Zone 7 oder 8 bin ich auf jeden Fall nicht zu finden.” Da schwang etwas Abneigung mit. So als würde Holden unter allen Umständen versuchen diese Zonen zu meiden. Das kam in den kargen Gesprächen während des Fluges so gar nicht zum Ausdruck. Doch jetzt, auf der Erde merkte ich diesen Unterton plötzlich. Vorher war er mir nicht bewusst geworden. Vielleicht war es Zufall und ich musste nichts darauf geben. Vielleicht aber hatte Holden auch eine Vergangenheit mit Vorfahren, welche noch von den Eugenischen Kriegen geprägt waren. So gibt es auch heute noch eine Vielzahl an Leuten denen alle Menschen mit Mutationen verhasst sind. Dabei ist ihnen durchaus egal ob es zufällige oder bewusst durch den Menschen herbeigeführte Mutationen sind.  Die Angst vor dem Anderen, die Angst vor dem Übermenschen der als Herrenrasse wieder die Welt unter sich aufteilt, gehört bei diesen Gruppen zum bestimmenden Teil ihres Weltbildes. 

Ich bestieg mein Flugtaxi und schloss die Tür. “Herzlich willkommen in der chinesischen Sonderverwaltungszone. Mein Name ist Sally und ich wünsche ihnen eine erholsame Fahrt. Ihr nächstes Ziel ist Zone 7 mit einem kurzen Umstieg in Tiānjīn shì. Wünschen Sie Musik?” “Hallo Sally” erwiderte ich. “Wieso Sonderverwaltungszone? Ich dachte das wäre das Gelbe Meer? Vielleicht etwas dezente Musik.” “Klassik?” fragte Sally. “Ja, gern aber leise.” “Wird sofort aufgelegt. Es spielt für Sie Carl Orff sein bekanntestes Werk *Carmina Burana*”. “Und ja, wir befinden uns im Gelben Meer, konkret in internationalen Gewässern. Da ich, Sally, ihr Flugtaxi, jedoch in Hongkong zugelassen bin, gelten die Beförderungsgesetze der Sonderverwaltungszone Hongkong während unserer Fahrt zum Festland. Im Übrigen bitte ich die Verwendung des Begriffes Fahrt zu entschuldigen. Natürlich handelt es sich eigentlich um einen Flug. Jedoch erfolgte meine Umrüstung zum Flugtaxi erst letztes Jahr. Das Softwareupdate in dem der Begriff Fahrt durch Flug ersetzt wird, soll erst Ende des Jahres erscheinen. Sorry dafür. Diese kleine Info wurde aber schon vorab durch einen Hotfix bereitgestellt. Dieser wurde finanziert von Hongkong Cars - DIE Vereinigung der bedeutendsten Taxiunternehmen. Wir wünschen allseits eine gute Fahrt.” “Danke Sally. Ich möchte mich gern noch ein wenig ausruhen, daher bitte smalltalk aus.” “Na schön, wie der Herr wünschen.” vernahm ich Sallies gekränkte Stimme. Diese Biochips mit Emotionen aus “Mona Lisa Overdrive” waren echt der Hammer und offensichtlich bereits im echten Leben angekommen. 

Der restliche Flug zum Festland verlief entsprechend ruhig und war auch sehr kurz. Keine halbe Stunde und ich betrat chinesisches Gebiet im Hafen von Tiānjīn shì. Dort musste ich in ein bereits wartendes Taxi umsteigen, welches keine Flugeigenschaften besaß.“Herzlich willkommen in der chinesischen Freihandelszone. Mein Name ist Lizzy und ich darf Sie auf unsere Fahrt nach Zone 7 herzlich willkommen heißen. Wünschen Sie Musik?” “Vielen Dank Lizzy, vielleicht etwas dezente Musik.” “Klassik?” “Gerne.” “Wird sofort aufgelegt. Sie hören Carl Orff mit seinem berühmtesten Werk *Carmina Burana*.” Ja so ist es mit der eingebauten Menschlichkeit - irgendwann wird sie langweilig. “Lizzy, könntest Du bitte Auskopplungen aus Cats oder Chess spielen?” “Wird sofort aufgelegt. Sie hören Murray Head mit ihrem größten Hit *One Night in Bangkok* aus dem Musical Chess.” Uuups, das ging wohl daneben. Die 80er im vor vorigen Jahrhundert - na gut das trifft auch meinen Geschmack aber ist nicht gerade Klassik ;-). Zumindest noch nicht :-).
