== Die Umfrage

[quote, Tom Borg]
Ich brauche keine Meinungsumfrage, um zu wissen, was ich für richtig halte.

Ich sitze entspannt am Tisch und lese auf dem Tablet meine eMails. "Oh eine neue Umfrage von Civey. 
link:https://civey.com/umfragen/6139/wie-haufig-kaufen-sie-im-supermarkt-produkte-die-nicht-auf-ihrem-einkaufszettel-stehen
[Wie oft kaufen Sie Produkte die nicht auf dem Einkaufzettel stehen?,role=external,window=_blank]" Ich klicke den Button welcher mich zur Umfrage führt. Das dachte ich mir, es gibt nur die Antworten "Immer", "Meistens", "Gelegentlich", "Selten" und "Nie". Dann drücke ich auf "Meistens". Eine Antwort wie sie Umfragen wollen, spontan und ehrlich. In gewohnter Manie beginne ich nun mir Gedanken über die Auswirkung dieser Antwort zu machen. Da mir die Antworten der anderen Menschen jetzt ebenso angezeigt werden ist zu erkennen, oder zumindest interpretiere ich das Bild so, dass es den meisten Menschen peinlich ist wenn sie sich nicht an ihren Einkaufzettel gehalten haben. Ist das so? Oder sieht es nur für mich so aus? 

Da ich nach meiner Schulausbildung direkt eine Lehre in einem Internat begonnen habe, war ich relativ früh auf mich selbst gestellt. Zu jener Zeit war das normal
und unsere Eltern und Großeltern mussten noch früher selbstständig werden, doch heute erscheint das nach der Schule und damit
mit 15 Jahren ausgesprochen früh zu sein. Nun in dem Alter hatte ich keine großen Geldmittel und ich musste zusehen, dass ich damit auskam. So kaufte ich natürlich 
nur wirklich wichtige Dinge die ich auch benötigte. Als Luxusgüter kamen dann noch Alkohol und Zigaretten oben drauf. Die ich beide zwar überhaupt nicht benötigte aber
die ich mir einfach als Belohnung fürs Überleben gönnte. So kam es, dass ich mein Leben lang vor dem Einkauf sorgfältig überlegte was ich brauchte und einen 
Einkaufzettel schrieb an den ich mich auch strikt hielt. 

In einem weit späteren Lebensabschnitt verfügte ich dann zwar über deutlich mehr Geld aber die Methode mit dem Zettel und dem Einkauf hielt sich weiter. Allerdings merkte ich auch, dass viele Trends die im Leben kommen und gehen von mir unbemerkt blieben. Spätestens als meine Kollegen neue Musik kannten von der ich noch nie etwas gehört hatte oder Begriffe wie Prepper oder Framing erklärten, die ich noch nie vorher gehört hatte, wurde ich skeptisch. Machte ich etwas falsch? Befand ich mich in einer ganz eigenen Informationsblase, in der sich die Anderen nicht befanden oder wie war es zu erklären, dass ich neue Trends nicht kannte? War ich wirklich Werbung gegenüber so unempfindlich wie ich es immer behauptete oder fehlten mir einfach wichtige Informationsquellen auf die Andere Zugriff hatten? Oder war es einfach so wie ich meinte, dass es war: Neue Trends sind einfach unwichtig, sie kommen und gehen und mir fehlt nix wenn ich sie nicht kannte oder mit gemacht habe. 

Und doch fehlte mir etwas - die Teilnahme am Gespräch. Wenn man Trends nicht kennt, kann man nicht mitreden. So flach das Gespräch auch sein mag, man sitzt beim 
Teamevent nur rum und langweilt sich. Gut es gibt Alkohol aber irgenwo hat auch der seine Grenze. Außerdem sind dessen Wirkungen verherender für das eigene Image als 
man sich je selbst eingesteht. Sei es wie es sei, ich war mit dem Zustand unzufrieden egal ob eingebildet oder nicht, ich wollte das evtl. bestehende Informationsdefizit beseitigen. Dazu erarbeitete ich mehrere Maßnahmen. Hier nur einige kurz aufgeführt. 

An Umfragen teilnehmen. Zwar sagte Gerhard Polt einst: "Auf Umfragen gebe ich keine Antwort, um Meinungsmüll zu vermeiden." und traf damit bei mir 100% auf Zustimmung, doch musste ich meine Meinung dazu im Laufe der Zeit revidieren. In Umfragen bekommt man Fragen gestellt z.B. "Wo haben Sie zuletzt Werbung der Firma XY gesehen?" Oft 
kenne ich diese Firmen gar nicht und damit ist ein bischen Informationsdefizit kompensiert. Wie gesagt unabhängig davon ob dies überhaupt notwendig wäre. Ich fühlte 
mich unwohl also war es wohl notwendig. Doch für mich gibt es noch einen viel wichtigeren Grund. Als Bürger hat man kaum Möglichkeiten auf Politik Einfluss auszuüben.
Entweder man steckt Geld in eine Lobbyvereinigung oder einen Lobbyisten der meine Interessen vertritt oder aber man versucht es selbst in der Politik oder nutzt 
Petitionen oder eben Meinungsumfragen. Denn wie bemerkte schon Franz Steinkühler sehr treffend: "Heute haben wir eine politische Elite, die fühlt sich nicht wohl,
wenn sie nicht jede Woche durch eine Meinungsumfrage bestätigt wird." Und genau das habe ich für mich als Mittel direkter demokratischer Mitwirkung erkannt. 
Die Politiker haben längst keine eigene Meinung mehr. Entweder vertreten sie die Meinung von Lobbyisten um mehr Geld zu verdienen oder sie vertreten die Meinung 
welche nach Umfragen den größten Rückhalt in der Bevölkerung hat und damit ihre Karriere sichert. Ergo nehme ich an Umfragen teil so oft es geht. 

Eine weitere Maßnahme war die Weiterbildung über selbstfinanzierte Onlinekurse. Nachdem ich diese Branche entdeckt hatte bemerkte ich, dass diese Kurse deutlich 
besser für meine Weiterbildung geeignet sind, als die Kurse welche ich vom Arbeitgeber finanziert bekomme. Die Konferenzen und Schulungen welche ich bezahlt vom 
Arbeitgeber besuchte, waren eher Prestige Veranstaltungen. Die Inhalte waren nicht wichtig. Wichtig war sehen und gesehen werden, vernetzten, sich kennen und vor
allem sich wiedererkennen wenn es drauf ankam. 

Aber auch im persönlichen Verhalten entdeckte ich Defizite, nämlich meinen Einkaufszettel. Er hinderte mich neue Dinge zu entdecken, denn was kaufte ich? Immer kaufte
ich was ich brauchte. Und was brauchte ich? Das hing von meiner Planung ab. Letzlich waren es Dinge für Essensgerichte, die ich kannte oder für Haushaltsmittel die ich
kannte. Alles was mir in meiner Kindheit und dem bisherigen Leben beigebracht oder ich erlebt hatte, aus diesem Fundus schöpfte ich und schrieb auf was ich daraus
wieder benötigte. Natürlich kamen keine Dinge auf den Einkaufszettel die ich nicht kannte, wie auch? Meine Entscheidung war, lass ihn bewußt weg diesen Einkaufszettel.
Der erste Einkauf ohne Zettel war ein schlimmes Erlebnis. Die Hälfte fehlte und ich musste nochmal los. Dafür waren Dinge im Korb gelandet die ich nicht kannte. 
Irgendwelche Früchte, von denen ich nicht einmal wußte ob diese essbar sind oder ob man sie erst kochen oder einlegen muß. Um so häufiger ich nun ohne Zettel einkaufen ging, umso mehr lernte ich kennen und um so besser trainierte ich mein Gehirn bzgl. einfach mal sich merken was man braucht. Allerdings musste ich mich auch an die 
neuen Preise gewöhnen, denn seit ich es akzeptierte, unnötige Dinge zu kaufen, seit dem gab ich auch mehr Geld aus. Irgendwann stellte ich aber fest, dass die 
Mehrausgaben mir nicht weh taten, ich aber dafür deutlich mehr Dinge kennen lernte. Das hinterlies bei mir ein zufriedenes Gefühl und ein paar Datensammlungen wie
beispielsweise die link:https://www.flickr.com/photos/huluvu424242/albums/72157648791128956[Sammlung der Früchte und wie sie gegessen werden,role=external,window=_blank]. 


