== Die Civey Umfrage

[quote, Epikur von Samos]
Mit dem Tod habe ich nichts zu schaffen. Bin ich, ist er nicht. Ist er, bin ich nicht.

Ich sitze entspannt am Tisch und lese auf dem Tablet meine eMails. "Oh eine neue Umfrage von Civey. 
link:https://civey.com/umfragen/6139/wie-haufig-kaufen-sie-im-supermarkt-produkte-die-nicht-auf-ihrem-einkaufszettel-stehen
[Wie oft kaufen Sie Produkte die nicht auf dem Einkaufzettel stehen?]" Ich klicke den Button welcher mich zur Umfrage führt. Das dachte ich mir, es gibt nur die Antworten
"Immer", "Meistens", "Gelegentlich", "Selten" und "Nie". Dann drücke ich auf "Meistens". Eine Antwort wie sie Umfragen wollen, spontan und ehrlich. In gewohnter Manie 
beginne ich nun mir Gedanken über die Auswirkung dieser Antwort zu machen. Da mir die Antworten der anderen Menschen jetzt ebenso angezeigt werden ist zu erkennen, oder 
zumindest interpretiere ich das Bild so, dass es den meisten Menschen peinlich ist wenn sie sich nicht an ihren Einkaufzettel gehalten haben. Ist das so? Oder sieht es 
nur für mich so aus? 

Da ich nach meiner Schulausbildung direkt eine Lehre in einem Internat begonnen habe, war ich relativ früh auf mich selbst gestellt. Zu jener Zeit war das normal
und unsere Eltern und Großeltern mussten noch früher selbstständig werden wie wir, doch heute erscheint das nach der Schule und damit
mit 15 Jahren ausgesprochen früh zu sein. Nun in dem Alter hatte ich keine großen Geldmittel und ich musste zusehen, dass ich damit auskam. So kaufte ich natürlich 
nur wirklich wichtige Dinge die ich auch benötigte. Als Luxusgüter kamen dann noch Alkohol und Zigaretten oben drauf. Die ich beide zwar überhaupt nicht benötigte aber
die ich mir einfach als Belohnung fürs Überleben gönnte. So kam es, dass ich mein Leben lang vor dem Einkauf sorgfältig überlegte was ich brauchte und einen 
Einkaufzettel schrieb an den ich mich auch strikt hielt. 

In einem weit späteren Lebensabschnitt verfügte ich dann zwar über deutlich mehr Geld aber die Methode mit dem Zettel und dem Einkauf hielt sich weiter. Allerdings merkte
ich, dass viele Trends die im Leben kommen und gehen von mir unbemerkt blieben. Spätestens als meine Kollegen neue Musik kannten von der ich noch nie etwas gehört hatte
oder Begriffe wie Prepper oder Framing erklärten, die ich noch nie vorher gehört hatte, wurde ich skeptisch. Machte ich etwas falsch, befand ich mich in einer ganz
eigenen Informationsblase in der sich die Anderen nicht befanden oder wie war es zu erklären, dass ich neue Trends nicht kannte? War ich wirklich Werbung gegenüber so
unempfindlich wie ich es immer behauptete oder fehlten mir einfach wichtige Informationsquellen auf die Andere Zugriff hatten?


