// Kurzgeschichte "Zone 7" 
== Der Geburtstag ist das Echo der Zeit
[quote, Charles de Montesquieu]
Wie schade, dass so wenig Raum ist zwischen der Zeit wo man zu jung, und der, wo man zu alt ist.

Es ist der 25.12. der Tag meiner Geburt und es ist fast Mittag. Wie jedes Jahr habe ich lange im Bett gedöst bevor ich mich aufraffen konnte aufzustehen. Zunächst einen Kaffee und etwas Stolle. Dann die Entscheidung - schauen ob wer gratuliert hat oder lieber nicht? Ich fühle mich mental stabil genug um zu verkraften wenn niemand an mich dachte ohne gleich in eine Depression zu rutschen und mir den Tag zu versauen. Also die üblichen verdächtigen abgeklappert, WhatsApp, Telegram, Facebook, Xing, eMail. Oh ha, doch etliche. Eine Kollegin, zwei ehemalige Kollegen und ein, nein zwei Familienangehörige, sowie diverse Leute aus der Schulzeit zu denen ich schon seit Jahrzehnten keinen Kontakt mehr habe. Jippi, das ist ein guter Tag heute. Am Nachmittag will Mark kurz vorbei kommen, dann sollte ich mal anfangen mich zu kultivieren und die Bude etwas zu ordnen. Scheint ein ganz netter Tag zu werden, ganz anders als in der Vergangenheit. 

Seit jeher hatte ich eher ein gespaltenes Verhältnis zu meinem Geburtstag. Es fing schon beim Datum an. Der 25.12. ein Tag welcher im Moloch als die Geburt Christus gefeiert wurde. So waren alle Familien im Urlaub und am 24. abends ging es in die Kirche anschließend Bescherung und am nächsten Tag besuchte man die Verwandten und gratulierte zum Weihnachtsfest. Wir gingen am 24. zu Oma und Opa meines Vaters und dort fand die Bescherung statt. Mein Vater war einer von 3 Brüdern, welche sich das ganze Jahr über verstritten hatten aber zu Weihnachten für Oma und Opa sich zusammen rafften. Einen Abend im Jahr sollten sich doch alle in der Familie mal vertragen können. Als ich größer wurde und Opa gestorben war, wurde zu Hause beschert. Dann ging es am 25. zur Oma und man traf sich auf ein bis zwei Stunden mit den Familien der Brüder. Dann zurück, nun noch die Geburtstagsgeschenke entgegen genommen und fertig - Weihnachten geschafft. 

Geburtstagsgäste? Ein oder zwei Mal in meiner Kindheit müssen andere Kinder zu Gast gewesen sein - ich kann mich kaum erinnern. Einzig was ich noch weiß ist, dass ich es als Quälerei empfand. Man musste sich an einen Plan halten, der vorher nicht besprochen wurde - die Eltern hatten sich halt was "tolles" ausgedacht und man musste mit machen. Also so wie jeden Tag, nun auch noch am Geburtstag - super. Am Ende habe ich immer geheult und die Kinder wurden nach Hause geschickt. So war ich an meinem Geburtstag zwar meist unter Menschen aber trotzdem immer irgendwie allein. Letztlich war es gar nicht so schlecht. Man gewöhnte sich daran und man konnte selbst bestimmen wie der Geburtstag abläuft wenn man alleine feiert. 

Beim Studium und im Arbeitsleben kam mir dann der Gedanke, dass ich scheinbar der Einzige bin der seinen Geburtstag alleine verbringt. So habe ich einmal beim Studium und zweimal im Arbeitsleben eine Geburtstagsfeier organisiert. Es lief auf Essen und Trinken hinaus und irgendwie hatten die Gäste ständig das Bedürfnis sich mit mir zu unterhalten und zwar alle zwanzig. Das war ich nicht gewöhnt, sonst fragte das ganze Jahr niemand nach meiner Meinung und nun sollte ich ständig mit allen reden? Das konnte ich gar nicht. Wenn man sonst nix zu sagen hat, fällt ein in solchen Situationen auch nichts ein was man sagen könnte. Ich war froh wenn sich alle untereinander unterhielten, so wie sonst auch, und ich meine Ruhe dabei hatte. Einige Gäste haben es mir offensichtlich übel genommen, dass ich mich zum Geburtstag nicht explizit um sie gekümmert habe. Allerdings wurde ich auf Geburtstagen zu denen ich eingeladen wurde, vom Gastgeber auch immer allein gelassen. "Unterhalt Dich doch mal mit dem oder jenen oder kennst Du X schon?" Das waren so die Sätze mit denen mir die Gastgeber klar machten, dass sie jetzt gerade keine Zeit für mich haben. Warum sollte ich das anders machen. Letztlich habe ich alle Erfahrungen im Umgang mit Gästen genau auf diesen Ereignissen gesammelt. Nach diesen Versuchen stellte sich heraus, dass niemand von meinen Gästen meinte mich auch einmal wieder einladen zu müssen. So fasste ich den Entschluss keine Geburtstagsfeiern mehr auszurichten. Offensichtlich war es eine vergebliche Mühe und zu Ehren meiner Geburt scheint auch nicht wirklich jemand gekommen zu sein. 


