// Kurzgeschichte "Zone 7" 
== Der Geburtstag ist das Echo der Zeit
[quote, Charles de Montesquieu]
Wie schade, dass so wenig Raum ist zwischen der Zeit wo man zu jung, und der, wo man zu alt ist.

Es ist der 25.12. der Tag meiner Geburt und es ist fast Mittag. Wie jedes Jahr habe ich lange im Bett gedöst bevor ich mich aufraffen konnte aufzustehen. Zunächst einen Kaffee und etwas Stolle. Dann die Entscheidung - schauen ob wer gratuliert hat oder lieber nicht? Ich fühle mich mental stabil genug um zu verkraften wenn niemand an mich dachte ohne gleich in eine Depression zu rutschen und mir den Tag zu versauen. Also die üblichen verdächtigen abgeklappert, WhatsApp, Telegram, Facebook, Xing, eMail. Oh ha, doch etliche. Eine Kollegin, zwei ehemalige Kollegen und ein, nein zwei Familienangehörige, sowie diverse Leute aus der Schulzeit zu denen ich schon seit Jahrzehnten keinen Kontakt mehr habe. Jippi, das ist ein guter Tag heute. Am Nachmittag will Mark kurz vorbei kommen, dann sollte ich mal anfangen mich zu kultivieren und die Bude etwas zu ordnen. Scheint ein ganz netter Tag zu werden, ganz anders als in der Vergangenheit. 

Seit jeher hatte ich eher ein gespaltenes Verhältnis zu meinem Geburtstag. Es fing schon beim Datum an. Der 25.12. ein Tag welcher im Moloch als die Geburt Christus gefeiert wurde. So waren alle Familien im Urlaub und am 24. abends ging es in die Kirche anschließend Bescherung und am nächsten Tag besuchte man die Verwandten und gratulierte zum Weihnachtsfest. Wir gingen am 24. zu Oma und Opa meines Vaters und dort fand die Bescherung statt. Mein Vater war einer von 3 Brüdern, welche sich das ganze Jahr über verstritten hatten aber zu Weihnachten für Oma und Opa sich zusammen rafften. Einen Abend im Jahr sollten sich doch alle in der Familie mal vertragen können. Als ich größer wurde und Opa gestorben war, wurde zu Hause beschert. Dann ging es am 25. zur Oma und man traf sich auf ein bis zwei Stunden mit den Familien der Brüder. Dann zurück, nun noch die Geburtstagsgeschenke entgegen genommen und fertig - Weihnachten geschafft. 

Geburtstagsgäste? Ein oder zwei Mal in meiner Kindheit müssen andere Kinder zu Gast gewesen sein - ich kann mich kaum erinnern. Einzig was ich noch weiß ist, dass ich es als Quälerei empfand. Man musste sich an einen Plan halten, der vorher nicht besprochen wurde - die Eltern hatten sich halt was "tolles" ausgedacht und man musste mit machen. Also so wie jeden Tag, nun auch noch am Geburtstag - super. Am Ende habe ich immer geheult und die Kinder wurden nach Hause geschickt. So war ich an meinem Geburtstag zwar meist unter Menschen aber trotzdem immer irgendwie allein. Letztlich war es gar nicht so schlecht. Man gewöhnte sich daran und man konnte selbst bestimmen wie der Geburtstag abläuft wenn man alleine feiert. 

Beim Studium und im Arbeitsleben kam mir dann der Gedanke, dass ich scheinbar der Einzige bin der seinen Geburtstag alleine verbringt. So habe ich einmal beim Studium und zweimal im Arbeitsleben eine Geburtstagsfeier organisiert. Es lief auf Essen und Trinken hinaus und irgendwie hatten die Gäste ständig das Bedürfnis sich mit mir zu unterhalten und zwar alle zwanzig. Das war ich nicht gewöhnt, sonst fragte das ganze Jahr niemand nach meiner Meinung und nun sollte ich ständig mit allen reden? Das konnte ich gar nicht. Wenn man sonst nix zu sagen hat, fällt ein in solchen Situationen auch nichts ein was man sagen könnte. Ich war froh wenn sich alle untereinander unterhielten, so wie sonst auch, und ich meine Ruhe dabei hatte. Einige Gäste haben es mir offensichtlich übel genommen, dass ich mich zum Geburtstag nicht explizit um sie gekümmert habe. Allerdings wurde ich auf Geburtstagen zu denen ich eingeladen wurde, vom Gastgeber auch immer allein gelassen. "Unterhalt Dich doch mal mit dem oder jenen oder kennst Du X schon?" Das waren so die Sätze mit denen mir die Gastgeber klar machten, dass sie jetzt gerade keine Zeit für mich hatten. Warum sollte ich das anders machen? Letztlich habe ich alle Erfahrungen im Umgang mit Gästen genau auf diesen Ereignissen gesammelt. Nach diesen Versuchen stellte sich heraus, dass niemand von meinen Gästen meinte mich auch einmal wieder einladen zu müssen. So fasste ich den Entschluss keine Geburtstagsfeiern mehr auszurichten. Offensichtlich war es eine vergebliche Mühe und zu Ehren meiner Geburt scheint auch nicht wirklich jemand gekommen zu sein. 

Die Klingel unterbricht mich in meinen Gedanken, vor der Tür steht Mark. "Hallo Mark und ein frohes Fest noch. Komm doch herein.", "Ja Danke, ebenso und alles, alles Gute zum Geburtstag und dass sich alles erfüllt was Du Dir wünscht.", "Danke Mark. Komm setz Dich. Möchtest Du einen Kaffee?", "Ja sehr gern.".

Während Mark es sich auf dem Sofa bequem macht, serviere ich uns jeden einen Kaffee. "Na, der wievielte Gratulant bin ich eigentlich? Doch hoffentlich nicht der Erste?", "Nein, etwa der siebente oder so. Genau weiß ich es jetzt gar nicht." "Hat Deine Mutter schon gratuliert?" "Nein, sie hat vorhin geschrieben ich soll mal anrufen." "Oh, was da los? Ich dachte ihr telefoniert kaum?" "Ja, das finde ich auch sehr ungewöhnlich. Normal überweise ich zu ihren Geburtstag einen Geldbetrag von 100 und sie mir zu meinen einen Geldbetrag von 100. Dann wird noch per Messenger eine Grußbotschaft gesendet und das war es für gewöhnlich. Dieses Jahr will sie unbedingt telefonieren." "Naja, sie ist nicht mehr die jüngste. Vielleicht geht es ihr nicht so gut und sie will noch ein paar Dinge klären" "Genau das hab ich auch schon gedacht. Ob Du es glaubst oder nicht aber genau so dachte ich vor einer Stunde noch. Dann ist mir aber eingefallen, dass meine Schwester gerade zu Besuch bei ihr ist. Wirklich wichtige Dinge würde sie also gleich mit ihr besprechen, zumal unser Verhältnis irgendwie auch nicht mehr so herzlich ist seit dem Tod meines Vaters." "Na das ist doch nun auch schon wieder über 10 Jahre her. Vielleicht will sie sich auch mit Dir versöhnen. Du weißt doch, im Alter mag man sich nicht mehr unbedingt rumstreiten sondern eher gutes tun und harmonisch mit allen auskommen." "Ja kann sein, vielleicht hast Du Recht." "Habt ihr einen Termin ausgemacht?" "Nein, ich sollte schreiben wann ich Zeit habe aber ich war mir nicht sicher. Aus den Erfahrungen der Vergangenheit her habe ich immer ein bisl Angst mir mit solchen Anrufen den Tag zu versauen. Vielleicht schreib ich, sie sollte nacher 20:00 Uhr nochmal anrufen. Da schaut sie für gewöhnlich einen Krimi, so könnte sich der Anfruf auch nicht ewig in die Länge ziehen." "Ach das ist glaube nicht gut. Da gibst Du ihr ja echt keine Chance mal aus sich raus zu kommen. Vielleicht will sie einfach nur nett mit Dir reden. Warum rufst Du sie nicht jetzt gleich mal selber an. Dann würde sie auch sehen, dass sie Dir nicht so gleichgültig ist. Vielleicht denkt sie ja auch nur, dass sie Dich nicht stören will." "Meinst Du? Also ich weiß nicht." "Ach komm, und damit ihr unter Euch seid gehe ich kurz eine Runde ums Haus." "Nein auf keinen Fall. Du gehst jetzt nicht gleich wieder oder langweile ich Dich so sehr?" "Quatsch, natürlich nicht aber ich dachte falls es zu privat wird, sollte ich evtl. nicht dabei sein." "Nein Du bleibst auf jeden Fall hier. Eigentlich ist das gar nicht so eine schlechte Idee. Ich rufe an und sage das Du mit zuhörst und wünsche noch ein schönes Weihnachtsfest. Das ist vielleicht ein ganz guter Plan, da bin ich auch nicht so unsicher." "Na dann let's go." 

Also rief ich an und stellte auf laut. Jemand nimmt ab und ich sage: "Hallo ich bins, ich wollte noch schöne Weihnachten wünschen und bei mir ist mein Kollege Mark er wünscht auch noch ein frohes Fest." Dann höre ich wie der Höhrer weiter gegeben wird und es meldet sich ein: "Hahaha ha ha, wie siehst Du denn auf dem Foto aus?" "Welches Foto?" "Na was Du der Mutti heute früh geschickt hast. Das T-Shirt ist ja auch uralt und passt ja überhaupt nicht mehr. Hahaha ha ha. Also ich habe ja die letzten Jahre auch einige Pfunde zugelegt aber so viel. Das ist ja der Hammer. Ha ha ha. Wir wollten Dir alles Gute zum Geburtstag wünschen." "Ah ja, schönen Dank." "Hast Du in letzter Zeit so viel gegessen oder machst Du gar keinen Sport mehr? Wie ist denn das passiert? Das sieht ja wirklich schlimm aus. Das ist bestimmt die mangelnde Bewegung in der Pandemie oder? Na ich hatte ja auch kaum noch Bewegung aber so viel hab ich natürlich nicht zu gelegt. Ich esse ja auch nur wenig. Wenn man sich nicht mehr bewegt, kann man ja nicht einfach so weiter essen wie bisher. Da muss man sich schon einmal ein bisl überlegen was man wann isst. Ich gebe Dir mal die Mutti, die will auch was sagen." "Na Mensch, wie kannst Du denn so viel essen? Als Du geschrieben hattest das Du Fahrradtouren unternimmst habe ich doch gedacht, dass Du damit in etwa bei gleichen Gewicht bleibst. Also ich mache ja nun mindestens einmal die Woche eine Tour und ich sehe ja auch nicht so aus. Deine Schwester ist ja aus allen Wolken gefallen. Die muss immer noch lachen. Das ist doch nicht hübsch. Hörst Du? Bist Du noch dran?" Mir stockte der Atem. Was war das? Was werde ich gleich sagen bzw. tun? Sollte ich explodieren oder ganz gelassen den Monolog ignorieren? Ich wusste es nicht. Ich schaute auf Mark. Er schaute mich versteinert an und reagierte auch nicht. Kurz durchzuckten mich Erinnerungen. Vor einigen Jahren hatte ich in den sozialen Netzwerken ein aktuelles Foto meiner Schwester gefunden und war genauso geschockt. Sie war fett und alt geworden aber natürlich habe ich ihr das nicht gesagt oder geschrieben. Sollte ich das jetzt erwähnen? Ich denke nicht, das bringt ja nix. Doch was soll ich sagen? Der ganze brauchbare Inhalt des Telefonats bestand in "Alles Gute zum Geburtstag" und dafür hatte ich mich schon bedankt. 

Ich beschloss den kompletten Inhalt zu ignorieren und ein neues Thema zu beginnen aber welches? Die Familienchronik würde sich anbieten, dafür habe ich oft nach Informationen bei meiner Mutter gefragt. Also fing ich an mit: "Naja ich fühle mich eigentlich ganz wohl aber was ich mal noch fragen wollte. Du hattest doch zur Schulzeit eine Freundin welche in so einem kleinen 3 Häuser zählenden Nachbardorf wohnte. Die welche immer erst zu Dir gelaufen kam und mit der Du dann gemeinsam zur Schule ins andere Dorf gelaufen bist. Ist die eigentlich mit uns verwandt oder wie kam das, dass ihr so ständig zusammen ward, damals?" "Ach nein, das waren Umsiedler. Denen hatte man damals dieses kleine verlassene Dorf als Wohnraum zugewiesen. Das waren übrigens mindestens 13 Häuser. So klein war das Dorf gar nicht." Also gut der Themenwechsel war gelungen aber jetzt geht wieder der Klugscheißer Modus los. Als ich mich im Jugendalter mit meinem Fahrrad dort umgeschaut hatte um zu sehen ob man dort vielleicht nach der Schule hinziehen könnte,  existierten genau 3 Häuser in denen Menschen lebten. Teilweise habe ich mich auch mit diesen damals unterhalten. Die anderen Häuser waren komplett leer stehend und ein großer Teil der Scheiben war eingeschlagen, teilweise sogar die Türen oder Fenster vernagelt. Wollte ich ihr das jetzt mitteilen und in eine Diskussion einsteigen? Ich denke nicht. Eigentlich will ich jetzt wieder meine Ruhe haben. Also das Telefonat möglichst schnell beenden. 
"Ach, dann sind wir gar nicht verwandt. Na gut dann muss ich das wohl noch notieren, sonst vergesse ich es wieder. Oooh ich glaube unser Essen ist jetzt gerade fertig geworden. Da muss ich wohl Schluss machen. War schön Euch mal wieder gehört zu haben. Dann noch ein paar erholsame Tage und einen guten Rutsch ins Neue Jahr." "Ja Dir auch und mach mal ein bischen mehr Sport." "Ja alles klar, bis denne. Tschau". 

"Alter, was war das denn? Pass auf jetzt bleib mal hier sitzen und bevor Du was sagst trinken wir erstmal nen kleinen Schnappulus. Du sagtest das Du gern Sake dringst - da hab ich mir erlaubt ein paar Tropfen mit zu bringen" "Ja, danke. Siehst Du so ist das. Erst denke ich immer so viel nach was schiefgehen kann und dann wenn mir nichts einfällt, probiere ich's und prompt geht irgendwas schief womit ich nie gerechnet hätte. Ich meine das Telefonat hat jetzt fast 30 Minuten gedauert und ich habe gefühlt zwei Sätze gesagt aber was genau war jetzt der wichtige Grund oder der Inhalt den ich unbedingt erfahren musste?" "Ach komm Prost, jetzt beruhige Dich erstmal. Inzwischen verstehe ich voll was Du meinst aber es ist glaube das Beste das alles zu vergessen und gar nicht drüber nach zu denken." "Ja vermutlich - so mach ich das schon mein ganzes Leben lang aber ja - erstmal Prost." Natürlich ist Sake nicht gleich Sake. Mark hatte nicht Sake als Reiswein mitgebracht, welchen man normalerweise leicht erhitzt trinkt, sondern Sake Schnaps. Normalerweise besitzt dieser um die 60% Alkoholgehalt und stellt eine erhebliche Herausforderung beim Trinken dar. Der von Mark besaß aber um die 45% Alkoholgehalt und wärmte wohltuend beim Schlückchenweise hinunter gleiten in den Magen. Es war angenehm und ich glaube auch genau das was ich in dem Moment wirklich brauchte. Danach war mir innerlich warm und ich fühlte mich schlagartig wohl. Ist natürlich keine Dauerlösung bei Problemen aber zu einem feierlichen Anlass und einem solchen spontanen Schockerlebnis hat es irgendwie gerade gepasst. 





