[#vorbereitung]
== Sorgen sind wie Nudeln man macht sich immer zu viele
[quote, Oprah Winfrey]
Glück ist eine Frage der Vorbereitung, die Gelegenheit beim Schopf zu packen.

Wir schwelgten den restlichen Tag noch in Erinnerungen und gingen dann früh zu Bett. Am nächsten Morgen packte Mark
seine restlichen Sachen und verabschiedete sich in den Urlaub. Er überlies mir in dieser Zeit seine Wohnung. So
mußte er sich nicht um die Planzen und Tiere kümmern und ich konnte die Zeit nutzen um mir selbst eine Wohnung zu
suchen und mich auf meine erste Arbeitswoche vorzubereiten.

Ich ging in die Küche und bereitete mir erstmal einen Smootie zu. Irgendwie hatte ich mich Mark mit seinem Faibel
angesteckt möglichst oft Nahrungsmittel selbst zu zubereiten anstatt diese vom Replikator bereitstellen zu lassen.
Das schöne am Replikator war, dass er nicht nur fertige Gerichte herstellen konnte sondern auch Früchte und andere
Lebensmittel. So ließ ich mir zunächst folgende Zutaten vom Replikator bereitstellen:

* 73 ml Apfelsaft
* 10 ml Traubensaft
* 4 ml  Limettensaft
* 3 ml Passionsfruchtsaft

Außerdem orderte ich noch ein Glas Guaven- und ein Glas Litschimark. Vom Guavenmark nahm ich soviel, dass im Messbecher
der Eichstrich von 8 ml erreicht wurde. Beim Litschimark ging ich nur bis 2 ml. Anschließend mischte ich alles gut durch.
Letzlich entsteht ein süsser belebender Geschmack, so wie ich ihn zum Beginn eines gutes Tages mag.





[ xref:ErsterTag.adoc[In der Historie von AKW Ausstieg und Genomentschlüsselung] ]