// Kurzgeschichte "Zone 7" - Kapitel X
== Am Anfang war ich so beliebt ...

[quote, Epikur von Samos]
Mit dem Tod habe ich nichts zu schaffen. Bin ich, ist er nicht. Ist er, bin ich nicht.

Ich schaue auf die Uhr in dem kleinen Krankenzimmer der Heilenden Häuser in Zone 7. Sie zeigt auf
5 vor 12. Wie passend denke ich. Da liege ich nun und weiß das meine Zeit fast um ist. Schreibe
die letzten Seiten in mein nur sporadisch geführtes xref:../tagebuch.adoc[Tagebuch]. Die Schmerzen
lassen sich nur noch mit Morphinen unterdrücken und alles was ich hoffe ist, dass mein Enkel erscheint.
Er hat es versprochen. Es ist kaum zu schaffen, die Entfernung ist zu weit, doch Nick will es versuchen.

Letztlich ist er der Einzige im Verwandten- und Freundeskreis welcher sich für Geschichte und auch
für die Geschichte unserer Familie interessiert. Ich werde ihm alle meine Aufzeichnungen erläutern
und dann werde ich sie ihm übergeben. Hoffentlich kommt er damit klar, hoffentlich kann ich alle
Fragen schon jetzt beantworten, denn später werde ich keine Antworten mehr geben können.

Es ist schon witzig. Als ich geboren wurde, haben mich alle gelobt und ich wurde herumgereicht im Kreise
der Familie. Alle mochten mich. Die Eltern waren stolz. Doch um so älter ich wurde und um so eigenständiger
meine Gedanken und selbstbestimmter mein Handeln wurde, desto Weniger mochten mich. Nun an dem Punkt
an dem das Ende naht, bin ich ganz alleine in einem Krankenzimmer. Fragen kommen mir in den Sinn:
"Hatte ich ein glückliches Leben geführt?", "War es schön?", "Habe ich alles erreicht, was ich erreichen wollte?"
Sie laufen immer auf die eine und Einzige Frage hinaus - habe ich so gelebt wie ich es wollte?

"Ganz ehrlich? - Ich weiß es nicht. Wie wollte ich denn leben?" Nicht einmal das weiß ich! Auf jeden
Fall wollte ich den Menschen etwas Gutes tun, ich wollte nützlich für die Gesellschaft sein, vielleicht
sogar etwas von Wert schaffen an das sich andere Personen die mich kannten noch erinnern werden.
Ich wollte mich nicht durch Arbeit kaputt machen für höhere Ziele wie die Kumpels in der Wismut. Nein,
stets wollte ich auch meine Gesundheit im Auge behalten. Ja ich wollte helfen aber mich dabei nicht
opfern. Es sollte ein faires Leben sein, den Anderen gegenüber. Ich wollte nicht nach dem Motto leben
"Leben jeden Tag als wäre es Dein Letzter.". Nein ich wollte nicht viel Reisen, nicht nur dauernd feiern
und das Leben in teuren Hotels oder bekannten Orten verbringen. Idealerweise würde ich ein Programm
schreiben welches vielen Menschen hilft und das wars. Familie gründen, Kinder aufziehen - das war eher
nichts was ich für erstrebenswert hielt. Warum sollte man Kinder in eine völlig verdorbene Welt setzen
und sich den Stress ihrer Aufzucht antun? Und was davon habe ich erreicht?

Wohl eher wenig. Zu meinem Erstaunen ist das Beste, dass ich im Leben hinbekommen habe die behütete
Entwicklung meines Sohnes. Ich war streng, teilweise zu streng und ich war ein Diktator - genau wie
ich es als Kind gelernt hatte. Das war nicht so gut aber es scheint keine schlimmen Folgen hinterlassen
zu haben. Zumindest hoffe ich das. Pädagogisch war ich eine Niete aber in Richtung Bildung und Arbeit
habe ich ihn nach Leibeskräften unterstützt. Das hat sich aus meiner Sicht gelohnt. Ich habe einen Sohn
der einen anständigen Charakter besitzt, höfflich, anständig, arbeitswillig und pflichtbewußt ist. Ja
ich bin durchaus stolz auf ihn. Er hat seinen Weg gemacht und seinen Platz im Leben gefunden. Hat eine
sehr gute Frau gefunden und uns einen weiteren Enkel geschenkt.

Schließlich habe ich im Laufe meines Lebens noch viel recherchiert und selber gelernt und mir sehr
viel Wissen angeeignet, so dass ich es Schade fände wenn dieses Wissen verloren geht. Darum hoffe ich
inständig, dass es Nick schafft noch rechtzeitig zu kommen. Es gibt so vieles das ich ihm noch erzählen
möchte. Doch wo fange ich an? Erzähle ich ihm von unseren Aufbruch ins Neuland
oder lieber doch gleich von meiner Arbeit in Zone 7? Ich denke es wird einfacher werden wenn ich mit
xref:AbschiedFloridaArklab.adoc[Zone 7] beginne.


