== Feindliche Übernahme
[quote,  Manfred Rommel]
Man muss die Fahne dort wehen lassen, wo der Sieg winkt.


Sie kamen und boten uns ihre Hilfe an. Sie taten so als ob sie uns aus dem Joch erlösen wollten. Zuerst verbesserten Sie unsere Sprache. Sie eliminierten schleichend unseren Wortschatz und ersetzten ihn durch den Ihren. Sie unterwanderten unsere Ämter und Behörden. Dann erließen sie neue Gesetze und Vorschriften und vertrieben viele von uns aus leitenden Positionen der Betriebe. Sie ordneten die Überprüfung aller an, die von uns noch in Ämter und Behörden arbeiteten. Wer nicht zu Ihrer Linie passte wurde entlassen - es waren viele, sehr viele. Die Straßen füllten sich mit ihnen doch sie gingen nur stumm daher. Dann wurden die Straßen umbenannt, die Plätze sogar ganze Städte - nichts sollte an uns erinnern. Letztlich eigneten Sie sich unsere Betriebe an. Die profitablen Abteilungen wurden neu entworfen und effizienter gestaltet. Freiwerdendes Personal wurde entlassen. Die nicht profitablen Bereiche wurden verkauft und die Belegschaft komplett entlassen. Es entstand ein Moloch an menschlichem Material, arbeitslos, hungrig, deprimiert und voller Angst vor dem was noch kommen mag. Aus diesem Brei suchten sie sich nach und nach die Besten heraus und ließen sie in Ihren Betrieben arbeiten aber nicht bei uns sondern in ihren Regionen. In Fabriken fernab des entstandenen Molochs, fernab unserer Heimat, fernab gewohnter Umgebung,  Kultur, Sprache  und sozialer Bindungen. Ihre Betriebe waren völlig anders organisiert. Nicht nach sozialen Bedürfnissen sondern nach Effizienz, Effektivität und Funktionalität. Sie wirkten steril und ähnelten irgendwie einer Scheinwelt. Das ganze Umfeld erschien nicht wirklich real. Die Menschen lebten angepasst. Sie vertraten ihre Meinung - jeder eine Andere aber immer scheinbar die ihre und doch irgendwie gekünstelt. Sie lachten wie auf Befehl an der passenden Stelle und nur an der passenden Stelle. Sie tadelten nicht, sondern lobten wenn sich Gelegenheit dazu bot. Ständig fühlte man sich verarscht aber man machte mit, man machte weiter, man brauchte das Geld, die Zeiten waren hart, eine Wohnung war teuer und man selbst war privilegiert, denn: man hatte Arbeit. Arbeit war alles. Arbeit hieß Geld, Arbeit hieß Wohnung, Arbeit hieß Nahrung und Arbeit hieß bis zu einem gewissen Grad auch Luxus. Viele von uns lernten schnell sich anzupassen - zu schnell wie sich später zeigen sollte. Die neue Sprache konnten sie schon perfekt, sie waren flink. Sie sogen alles Neue auf. Sie gingen mit Ihnen in neue Regionen von denen sie früher nie hoffen durften diese jemals auch nur sehen zu können. Sie genossen das Leben, machten sich keine Sorgen und ließen der Welt ihren Lauf. Sie feierten tagaus tagein und machten sich über nicht so schlaue Menschen lustig und nutzen diese aus. Sie passten sich so gut an, dass sie kaum noch vom Vorbild unterschieden werden konnten. Sie verleugneten ihre eigene Herkunft bis sie selbst glaubten nie ein anderes Leben geführt zu haben. Trotzdem erkannte man sie mit der Zeit alle - die Vorbilder genau wie ihre Klone. Nur Wenigen wie mir viel diese Anpassung nicht so leicht. Warum eigentlich nicht? Ich konnte es nicht. Ich wollte es nicht. Ich war zornig, vor den Kopf gestoßen, betrogen. Betrogen um den Rest meines Lebens. Schließlich war zum Beginn alles ganz anders gedacht gewesen oder dachte nur ich mir es anders? Sollte ich der Einzige sein der es sich anders vorgestellt hatte?
