== Zurück auf Null
[quote, Konfuzius]
Zu einem guten Ende gehört auch ein guter Beginn

Ein Geräusch reißt mich aus dem Schlaf. Ich öffne die Augen und erblicke eine fremde Wohnung. Wo bin ich? Welcher Tag ist? Langsam erhebe ich mich von meiner Luftmatratze und wanke zum Fenster. Auf dem Weg dorthin muss ich einige Säcke mit Sachen und noch nicht am richtigen Platz stehende Möbelstücke umlaufen. Ja der Umzug - Gott sei Dank geschafft. Es war meine erste Nacht in der neuen Wohnung und nicht nur das, es war meine erste Nacht in Ihrem Gebiet. 
Seit der Übernahme waren einige Jahre vergangen und das Leben im Moloch war unerträglich geworden. Nicht für mich da es mir als Student wirklich gut ging. Aber so viel man auch wissen möchte und so lang man auch studiert - irgendwann endet auch das längste Studium. Zwar hätte ich bequem ein neues Studium beginnen können aber das hätte ich auch selbst bezahlen müssen. Die “Studiengebühr” an sich war nicht hoch aber hinzu kamen noch die Kosten für Unterbringung und Lebensmittel. Das konnte ich nicht mit einem Job als studentische Hilfskraft stemmen und bei einem Vollzeitjob wäre keine Zeit für das Studium selbst geblieben. Also war alles was mir übrig blieb eine Arbeit zu suchen. Doch im Moloch gab es kaum Arbeit und wenn dann nur zu unmenschlichen Bedingungen. Also bewarb ich mich bei Ihnen - bei den “Neuen”. Nach einiger Zeit hatte ich damit Erfolg und nun war ich angekommen in meinem neuen Leben.
Gestern, Samstag,  war ich eingezogen. Von den Nachbarn hatte ich während des Einzugs niemanden entdeckt. Doch nun da ich am Fenster stand sah ich wie sich vor dem Haus hektisches Treiben ausbreitete. Die Leuten strömten aus ihren Häusern mit Kind und Kegel und bewegten sich in Richtung Stadt. Es war gerade 09:30 Uhr vermutlich gingen viele von ihnen zur Kirche. Ich bin zwar getauft und konfirmiert und somit wohl auch Christ dennoch zog mich die Kirche nicht an. Die scheinheiligen Reden der Pfarrer, das geheuchelte Mitleid der Gemeinde, das alles war nichts für mich. Ja das war auch mal anders! Damals als die Pfarrer noch zur Revolution aufriefen und jeder Gang zur Kirche den Beigeschmack eines Geheimtreffens hatte. Ja damals bin ich noch gern zur Kirche gegangen aber das ist lange her. Inzwischen überlege ich mir schon länger auszutreten. Der einzige Grund warum ich es noch nicht getan habe sind meine Eltern. Man will Eltern einfach nicht enttäuschen zumindest nicht auch noch in solchen belanglosen Dingen. Schließlich waren sie es die mich getauft hatten. Reformiertapostolisch getauft soweit ich weiß. Ich verwechselte schon immer ob ich nun der Neu- oder Reformiertapostolischen Gemeinde angehörte. Vermutlich weil ich nach der Taufe dann komplett evangelisch erzogen und auch so konfirmiert wurde. Es spielte in meinem Leben einfach keine Rolle. Da die meisten meiner Cousins neuapostolisch sind muss ich wohl reformiertapostolisch sein, denn soweit ich weiß hat mein Opa damals die Kirche gewechselt und sich so vom Rest der Familie distanziert. Doch waren meine Eltern überhaupt noch in der Kirche und wenn ja in welcher? Hatte meine Mutter nicht erwähnt sie seien ausgetreten aber das soll in der Familie keiner wissen? Da muss ich mal nachhacken beim nächsten Treffen. Wer weiß wann das sein wird. Als ich noch im Moloch wohnte war die Entfernung viel kürzer und selbst da habe ich es nicht jedes Jahr geschafft sie wenigstens einmal zu besuchen und jetzt? Jetzt wohne ich weit weg, da ist der nächste Besuch doch meistens die Beerdigung. Nein dazu darf ich es nicht kommen lassen, es gibt noch viel zu bereden, sie müssen mir noch viel erklären zu Entscheidungen in der Vergangenheit die für mich nicht nachvollziehbar sind. Nein ich muss das hier als Job sehen und ich muss verdammt schnell versuchen alte Kontakte und Freundschaften zu aktivieren jetzt wo ich hier bei den “Neuen” wohne. Fernab meiner Freunde und fernab meiner Kultur.
Doch zunächst muss ich dafür Sorgen, dass der Einstieg in den neuen Job gut läuft. Ich verrichte meine Morgentoilette und begebe mich in die Stadt. Da ich um ins Internet zu kommen ein Modem besitze bei dem ich dem Anbieter jeden Adresswechsel mitteilen muss damit er die Verbindung freischalten kann, brauche ich jetzt ein Internetcafé. Am Bahnhof werde ich fündig. Die Route zur Arbeit ist schnell ausgedruckt und ich mache mich auf den Weg. Mein Ziel: Arbeitsort finden und Zeit für den Weg zur Arbeit messen. Nachdem ich wieder bei meiner Wohnung angelangt bin ist es Nachmittag. Auf einer portablen elektrischen Heizplatte setze ich Reis auf, dazu eine Büchse Gulasch und im Nachgang eine Flasche Martini aus dem Netto. Das war es für heute, ich leg mich wieder auf die Luftmatratze. Am liebsten würde ich alles vergessen, wo ich bin, was ich bin, wer ich bin doch das geht nicht dauerhaft aber zumindest zeitweise. Der Alkohol beginnt zu wirken und ich schlafe ein.

