== Traum
[quote, Karl Valentin]
Die Zukunft war früher auch besser

In meinem Traum lebte ich bereits diverse Jahre im Gebiet der Neuen. Es war ein gewöhnlicher Tag und ich fuhr von der Arbeit heim. 
Seit der großen Feinstaubkatastrophe vor einigen Jahren hatte sich einiges verändert. Die öffentlichen Verkehrsmittel waren jetzt zum bersten gefüllt und fuhren rund um die Uhr fast ausschließlich im 5 Minuten Takt. Busse und Bahnen verfügten über eine neue, vollkommen überarbeitete Anordnung der Haltegriffe welche auf jeglichen stylischen Schnick Schnack verzichtete und irgendwie an die Halterungen aus den 1980er Jahren erinnerte. Back to the roots denke ich mir und muss ein wenig lächeln dabei. Durch die Anordnung der Halterungen war die Körpergröße nicht mehr relevant und so konnten sich vom Kind bis zum Greis alle Stehenden auch in den Gängen zwischen den Türen festhalten. Wäre die U-Bahn leerer gewesen hätte man bemerkt, dass die neuen Halterungen dazu führten, dass sich vor den Türen keinen Menschenknäuls mehr ausbildeten. So aber trat dieser Effekt in den Hintergrund, da jeder kleinste Raum im Wagon genutzt wurde.  Auch hatte nach über 20 Jahren U-Bahn irgend ein pfiffiger Mitarbeiter entdeckt dass im Schienenverkehr bereits seit Jahrzehnten Gepäckablagen üblich sind und auch die U-Bahnen damit versehen. Den Stauraum nahmen die Leute dankend an. Seit die Stadtverwaltung eine strikte Trennung zwischen Wohn- und Gewerberaum durchgesetzt hatte konnte praktisch jeder einen Arbeitsweg vorweisen. Die Trennung zwischen Wohn- und Gewerberaum bedeutete, dass alle Tätigkeiten welche nicht der Erholung und des Wohnens dienten in Gewerbegebiete außerhalb der Stadt ausgelagert wurden. Praktisch hieß das, dass es in der Stadt weder Geschäfte noch Büros noch andere Verkaufsstellen wie Bäcker etc. gab. Natürlich gab es Ausnahmen aber diese waren strikt definiert. So waren alle Bereiche welche der Sicherheit der Menschen dienten freilich weiterhin in der Stadt verfügbar. Dazu zählten ehemals Feuerwehr, Ärzte, Polizei, Rettungsdienste, Pflegedienste etc. Die einzelnen Ausprägungen gab es jedoch in der Form nicht mehr. Stattdessen gab es ein neues Konzept basierend auf dem Emergency Response Point - ERP. Diese Punkte wurden flächendeckend über das gesamte Stadtgebiet verteilt und vereinten die Aufgaben aller Sicherheitskräfte. Auch wurden hier Arzneimittel an die Bevölkerung ausgegeben so dass Apotheken im Stadtgebiet selbst nicht mehr zu finden waren. Der private Autoverkehr war im kompletten Stadtgebiet eingestellt und verboten wurden. Somit wurde der öffentliche Nahverkehr faktisch für jeden verpflichtend. Dafür war er endlich kostenfrei nutzbar und verfügte über spezialisierte Wagon’s mit denen sich auch größere Waren aus dem Gewerbegebiet in die Stadt transportieren ließen. Diese Wagons konnten per Internet auch reserviert werden. Selbst Elektroautos waren im Stadtgebiet verboten, da es nicht nur um die Verringerung des Feinstaubes ging sondern vor allem um die Schaffung von Ruhe und Erholungszonen für die Bevölkerung. Dennoch mussten die Straßen und Parkplätze nicht abgeschafft werden - im Gegenteil diese waren nun der Nutzung durch Sicherheitskräfte und Transportdienstleister vorbehalten. Letztere brachten die im Internet oder Gewerbegebiet bestellten Waren zur Bevölkerung und boten alle Services rund ums Wohnen. 
All dies waren die Folgen der Feinstaubkatastrophe. Die ersten Maßnahmen der Stadt waren mit Land und Bund abgestimmt und schienen keine großen Auswirkungen zu besitzen,  daher wurden sie auch einfach gegen den Willen der Bevölkerung durchgesetzt, was zu sehr großen Unmut und Massendemonstrationen im Land führte. Letztlich aber setzte sich der Staat durch und vermutlich war es pures Glück, dass die Rechnung zum Schluss aufging. Nun nachdem die neue Ordnung schon über 10 Jahre in Kraft ist hat man sich nicht nur daran gewöhnt sondern empfindet diese auch als einen gewissen Luxus. Das alles obgleich es eigentlich Zwangsmaßnahmen des Staates waren die erheblichen Einfluß auf die Entwicklungs- und Entfaltungsmöglichkeiten der Menschen nahmen. Schließlich siegte die Einsicht in die Notwendigkeit und alle Menschen hatten etwas davon gehabt. Keiner war wirklich unglücklich mit der neuen Ordnung nicht einmal extrem spekulativ umtriebige Firmen. Ja auch diese merkten, dass ihre Mitarbeiter plötzlich erholter zur Arbeit kamen und dort deutlich mehr leisteten. 
Das hektische Treiben fand nun innerhalb der Gewerbegebiete statt. Hier wurden die Dinge des täglichen Bedarfes gekauft und per ÖPNV heim transportiert. Die Ladenschlussgesetze waren inzwischen gefallen und so konnte jeder auch außerhalb der Arbeitszeit diese Dinge ohne Streß und zusätzlichen Preisaufschlag bekommen. Der Fall der Ladenschlussgesetze kam mit dem Gesetz zur Gleichstellung von Angestellten des Emergency Bereichs. Das allerdings bedeutete nicht, dass nun wieder auf die alten Schichtsysteme zurückgegriffen wurde. Nein im Gegenteil, es war sogar üblich geworden alle Beschäftigungsverhältnisse über flexible Arbeitszeiten zu gestalten. Im Prinzip konnte man kommen und gehen wann man wollte, wichtig war nur, dass man seine Anwesenheit richtig verbuchte und natürlich die Mindestanwesenheitszeit nicht unterschritt. Im Gegenzug zu diesen Erleichterungen wurde der Kündigungsschutz drastisch verringert. Im Prinzip war er faktisch nicht mehr vorhanden. Wer ein Vergehen in der Firma beging oder seine Arbeit nicht schaffte oder auch einfach nicht ins Team passte konnte relativ zügig entlassen werden. 
Die Folge jahrzentelanger verfehlter Gewerkschaftspolitik mit der sich die Gewerkschaften zum großen Teil auch gleich selbst mit abgeschafft hatten. Zu lange ging es in den Gewerkschaften nur um Populismus, Kungelei, Postenbesetzung und neue Mitglieder. Bei einer Sitzung mit 6 Tagesordnungspunkten befassten sich im Prinzip 5 mit dem Anwerben neuer Mitglieder. Die letzte Sitzung an der ich teilnahm, stellte ein einzigartiges Beispiel dar. Sie verfügte über folgende Agenda: 1. Begrüßung der neuen Mitglieder 2. Vorbereitung der neuen Ausgabe der Vereinszeitung 3. Abstimmung zu den Details der neuen Tarifrunde im Februar 4. Werbeveranstaltung auf dem Markt 5. Flyerverteilung in der Firma 6. Was wollen wir dieses Jahr durchsetzen. Punkt 1 zog sich in die Länge und überschritt die anberaumte Zeit weil die alten Hasen plötzlich sehr schockiert dreinschauten über die Meinungen der neuen Mitglieder. Die Artikel der neuen Ausgabe der Vereinszeitung für Punkt 2 waren bereits geschrieben und es ging nur um Details zum Layout. Wichtigster Punkt war die Platzierung des Gewerkschaftslogos und des Anmeldeformulars, damit beeindruckte Mitarbeiter unverzüglich ihr Interesse bekunden konnten. Leider war der Punkt Inhalte diskutieren um die Leser zu beeindrucken nie auf einer Agenda erschienen. Im Punkt 3 ging es nur darum die Mitglieder zu befragen was sie vom Tarifabschluss erwarten. Wichtig dabei war allerdings, es ging nicht um den Tarif selber sondern Nichtmitglieder sollten ganz bewusst wahrnehmen dass die Gewerkschaftsmitglieder befragt wurden. Also das Vorgauckeln von Basisdemokratie zur Aquise. Nur die Kollegen nicht ansprechen wenn keiner im Raum ist. Punkt 4 war vollumfänglich auf die Gewinnung neuer Mitglieder ausgerichtet und auch in der Flyerverteilung ging es um nichts anderes. Punkt 6 musste auf Grund der vorangeschrittenen Zeit leider auf das nächste Treffen verschoben werden. 
Doch wie auch schon die vielen Jahre vorher so störte die Quasi Abschaffung der Gewerkschaften niemanden in der Bevölkerung da diese Vereine ohnehin nur noch verhöhnt wurden. Auch musste sich bei einer Kündigung keiner wirklich Sorgen um seine Zukunft machen da inzwischen ein Bedingungsloses Grundeinkommen eingeführt worden war. Der Betrag des BGE war gerade so hoch wie früher der Hartz IV Satz plus eine Pauschale für Miete und Energiekosten. Das hatte für den Staat den Vorteil das aufwendige Prüfungen zur Berechnung und Vergabe der Geldhöhe entfielen - es bekam einfach jeder die gleiche Höhe monatlich ausgezahlt. Nicht einmal ein Antrag war zu bearbeiten, da das BGE praktisch an jede volljährige Person ausgezahlt wurde und damit einfach per Meldeamt an die zu jedem Hauptwohnsitz hinterlegte Bankverbindung maschinell überwiesen wurde. Natürlich waren die Ämter inzwischen soweit vernetzt dass es nicht mehr möglich war zwei Hauptwohnsitze pro Person im Land zu melden. Das Ausland war nicht mehr interessant, da das BGE nur an inländische Hauptwohnsitze gezahlt wurde wenn die betreffende Person das 18. Lebensjahr vollendet hatte und mindestens 2 Jahre die Staatsbürgerschaft des Landes nachweisen konnte. Da diese Angaben ohnehin alle bereits im Aufgabengebiet des Meldeamtes vorlagen und dort überprüft wurden, konnte eine ganze Behörde welche sich vorher mit der Vergabe von Hartz IV Leistungen und deren Sanktionierung befasste abgewickelt werden. 
Plötzlich war ein lautes Krachen zu hören und ein gewaltiger Schlag riss mich zu Boden. Die U-Bahn hatte vollautomatisch eine Notbremsung eingeleitet. Langsam rappelte ich mich auf. Eine Stimme sprach von Personen im Gleisbett. Sie gab diverse Hinweise wie “Türen nicht öffnen”, “Ruhe bewahren”, “Nicht aussteigen”. Da die Stimme immer leiser wurde konnte ich die letzten Durchsagen nicht mehr verstehen. Auch wurde der Raum immer heller. Irgendeine gleißende Helligkeit war in den Tunnel eingedrungen und flutete alles mit Licht. 
