== Erster Arbeitstag
> Oh Herr sag warum soll ich arbeiten gehen wo die Erde doch alles gibt? - Weil Du arm bist!

Schweißgebadet und vom Lärm des Weckers genervt erwache ich aus meinem Traum. Die Sonne strahlt bereits hell in mein Zimmer und ich muß mich beeilen um den ausgearbeiteten Zeitplan einhalten zu können. Es ist bereits 07:00 Uhr als ich in die U-Bahn steige. Der U-Bahnhof ist überfüllt mit lärmenden Schülern. Dicht gedrängt stehen wir in der führerlosen U-Bahn. Am Hauptbahnhof lasse ich mich im dem Strom der Aussteigenden treiben und begebe mich zur Staßenbahnhaltestelle. Die nächste Bahn fährt bereits ein und die Aussteigenden versuchen auf dem schmalen Bahnsteig an den Wartenden vorbei zur Unterführung zu gelangen. Für alle Beteiligten eine logistische Herausforderung. Es sind nur etwa 10 Minuten Fahrt und schon bin ich am Ziel angekommen. Die Staßenbahn hält direkt vor einem 11 stöckigen Gebäude mit 2 seitlichen Ausläufern. Davor befindet sich ein Platz mit gläsernden Säulen an denen Wasser herunterrinnt - Wasserspiele. Diesen Platz muß ich überqueren um zum Eingang zu gelangen. Dabei gleitet mein Blick durch einen Durchgang des Gebäudes hinter dem ich ein Kunstobjekt erkenne. Von hier aus sieht es aus wie ein überdimensional großer Nagel. “Oh Gott” denke ich, wenn das nur kein Zeichen ist. Warum verziert man das Gebäude einer Behörde mit einem Kunstwerk welches den Eindruck erweckt es wäre bereits der erste Sargnagel daran befestigt wurden?  
Mir bleibt keine Zeit darüber weiter nach zu denken. Der Eingang ist nur mit speziellen Karten passierbar und ich besitze keine. Des Pförtner winkt mir zu. Ich solle zu einer kleinen Nebentür gehen und dort das Gebäude betreten. Diese Tür besitzt eine Klinke und nach dem Durchschreiten besteht die einzige Fluchtmöglichkeit in Richtung Pförtner. Aha alles auf Sicherheit ausgelegt - die müssen ganz schön Angst haben hier - vor wem auch immer. Ich zeige dem Pförtner mein Einladungsschreiben und er weist mir den Weg zum Fahrstuhl. Ich will mich gerade zu den Wartenden an den 6 Fahrstuhlschächten gesellen als eine Fahrstuhltür sich öffnet. Vier Personen steigen aus und 2 ein die Anderen warten weiter. Ich ergreife die Gelegenheit und steige schnell noch mit ein. Mein Blick sucht die Tafel mit den Knöpfen zur Etagenauswahl - alle schauen mich an. “Ich möchte in die 10. Etage - wo muss ich da bitte drücken?”. Beide grinsen. Da müssen Sie draußen an dem Kasten in der Mitte die 10 drücken und ablesen welchen Fahrstuhl sie nehmen soll. Ah danke, stammel ich verwirrt und verlasse schnell noch die Kabine bevor sich die Tür vollständig schließt. Jetzt ist schon mal klar warum der Rest also noch wartet. Der schwarze Kasten entpuppt sich als Tetraeder welche auf jeder Seite (außer der Bodenfläche) mit einem Touchscreen ausgestattet ist. Darauf befinden sich die einzelnen Etagen aufgelistet. Als ich auf die 10 drücke erscheint kurz Fahrstuhl 4 auf dem Display. Am Sockel unter dem Tetraeder befinden sich noch RFID Lesegeräte deren Aufgabe mir nicht ersichtlich ist. In Anbetracht der voranschreitenden Zeit denke ich auch nicht weiter darüber nach und nehme meine Wartepostion vor dem Fahrstuhl 4 ein. Endlich öffnet sich die Kabinentür und ich trete gemeinsam mit anderen Personen ein. Auf den vielen Etagen bis zur 10. steigen alle Personen aus, so dass ich nur noch allein die Etage betrete. Mein erster Eindruck: nichts. Das surren der Klimaanlage ist zu hören und es bietet sich ein herrlicher Blick über die Stadt durch die hermetisch dichten Doppelglasfenster welche über keinen Mechanismus zum Öffnen verfügen. Nur Menschen sehe ich keine und nach Arbeit sieht es hier auch nicht aus. In drei Richtungen erstrecken sich scheinbar endlos lange Gänge mit diversen Büros welche Tür an Tür liegen - doch kein geschäftiges Treiben ist zu sehen. Ich suche das Zimmer welches auf meiner Einladung steht und klopfe. Ein freundliches Herein erschallt. Sie sind die Neueinstellung und kommen wegen der Bilder für die Zugangskarte? “Ja - ich denke schon. Stand so jetzt nicht auf der Einladung aber kann schon sein.” Zeigen Sie mal her. Ja, ja das hat schon seine Ordnung. Setzen Sie sich bitte dort drüben auf den Stuhl mit den Beinen in Richtung Tisch und drehen Sie den Oberkörper bitte so dass Sie in diese Kamera schauen. Bitte nicht lächeln das Foto muss den Richtlinien der Biometrieerkennung entsprechen. Vielen Dank das war es schon - wenn Sie dann bitte draußen warten würden. “Ja natürlich”. Während der Wartezeit erscheint ein Mann im Flur und kommt auf mich zu. Ich erkenne ihn wieder, er war bei meinem Einstellungsgespräch dabei und hat mir viele Fragen gestellt aber auch erwähnt, dass wir die Einstellung noch vor dem ersten des Folgemonats durchziehen müssen wenn ich bei meiner Gehaltsvorstellung bleibe. Im nächsten Monat würde meine Stelle nur noch mit einer geringeren Tarifstufe vergütet. Wir begrüßen uns freundlich dann öffnet sich auch schon die Tür. So ihre Zugangskarte - bitte sehr. “Danke”. Dann kann es ja gleich losgehen, sagt der Mann welchen ich mir unter dem Namen Leikler gemerkt habe. Ihre Arbeitsstelle befindet sich in einer Auslagerung. Am besten wir fahren gleich rüber damit ich Sie mit Ihren Kollegen bekannt machen kann. Wir begeben uns in Richtung Fahrstuhl. Er scheint mir deutlich älter als ich und etwas größer. Auch schreitet er deutlich schneller als ich voran - vielleicht wegen der längeren Beine, vielleicht aber auch nur aus Gewohnheit. Kurz vor den Fahrstuhlschächten schwenkt er abruppt in Richtung Wand auf einen Notausgang zu. “Ich nehme immer die Treppe” sagt er. “Ok” höre ich mich sagen und mein Gehirn fängt an zu rechnen: 10 Etagen = 20 Halbtreppen a mindestens 10 Stufen - ist das ein Test? Später einmal werde ich feststellen, dass es kein Test ist. Es ist sein persönliches Training um sich fit zu halten. Ob auf dem Weg zum Mittagessen und zurück oder nur kurz zum Meeting - er nimmt immer die Treppe. Als wir uns beim Pförtner verabschieden bin ich bereits etwas verschwitzt und der ganze Arbeitstag liegt noch vor mir. Nun gut das muß ich wohl demnächst berücksichtigen.
Wir nehmen einen ähnlichen Weg durch die Stadt, zunächst Straßenbahn dann U-Bahn, dann sind wir am Ziel. Das Gebäude gehört einem Pharma Konzern. Wir fahren bis in die 4. Etage.

