== Rückseite des Buches

Nachdem auf der Erde im 21. Jahrhundert, die als “Dritten Weltkriege” in den Geschichtsbüchern verzeichneten internationalen Kriege in einer atomaren Katastrophe endeten, welche zwar nicht zum Erlöschen der Menschheit führten jedoch große Teile des Planeten für viele Jahrtausende verseuchen sollten, begann die Menschheit andere Orte im Sonnensystem zu besiedeln. Dabei wurden besonders die Zwergplaneten Ceres, Pallas und Vesta im Hauptasteroidengürtel des Sonnensystems wie auch viele Monde zur Gründung neuer Nationen auserkoren. Nur einige Urvölker der Amazonasgebiete wie auch Teile der Aboriginies Australiens blieben zurück. Natürlich blieben auch all jene zurück welche die Kosten für einen Flug zu den Auswanderungsgebieten nicht aufbringen konnten. Sie waren das Leben ohne Zivilisation in der Regel nicht gewöhnt und dadurch gegenüber den Urvölkern benachteiligt im Kampf ums Überleben. Aus der Not heraus entstanden viele friedliche Kooperationen zwischen den neuen Standorten um das Überleben der Menschheit sichern zu können. Doch die Menschen wären nicht die Menschen wenn Sie es dabei belassen würden. So fanden sich auch jetzt bald wieder erste Bemühungen einzelne Verträge zu unterwandern und andere Nationen zu unterjochen. Die Geschichte “Neuland” ist eine Geschichte über banale Alltäglichkeiten in dieser Zeit. 

=== Streiflichter aus den Redaktionen

“Größtenteils harmlose Begebenheiten am Rande der Milchstraße” titelt der “Anhalter durch die Galaxis”.

“Eine geniale Anleitung zur Zerstörung ganzer Nationen” heißt es in den großen Werken der Encyclopedia Galactica über das Buch.

“Sie kannten keine Telefondesinfizierer und kamen dennoch um.”  schreibt Mark Watney in einem auf dem Mars verschollenen Tagebuch. 

“Eine Besiedlung der Asteroiden war nur auf Grund meiner detaillierten Beschreibungen  überhaupt möglich” hebt James S. A. Corey in einer Ansprache auf dem Mond der Erde hervor. 

